
<expression> ::= <term> { ("+" | "-") <term> };
<term> ::= <power> { ( "*" | "/") <power> };
<power> ::= <identifier> {"**" <identifier>};
<identifier> ::= <id> | <number> | "(" <expression> ")";
<id> ::= STRING;
<number> ::= NUMBER;